sample/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  #resources :folders
  resources :photos
  Bucketerize::Routing.mount '/bucketerize', as: 'bucketerize'
  mount PlayAuth::Engine => '/auth', :as => :auth
  root 'photos#index'
end

sample/app/models/folder.rb
class Folder
  include Bucketerize::Concerns::Bucket
  act_as_bucket collect: :photo
end

sample/app/models/photo.rb
class Photo
  include Bucketerize::Concerns::Resource
  act_as_bucket_resource mode: :multi, into: :folder
end

sample/app/models/project.rb
class Project
  include Bucketerize::Concerns::Resource
  act_as_bucket_resource mode: :standard
end

sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sample/app/controllers/folders_controller.rb
class FoldersController < Bucketerize::BucketsController
end

sample/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params[:photo]
    end
end

sample/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project]
    end
end

sample/app/views/layouts/_message.html.erb
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <%= msg %>
  <%#= content_tag :div, msg, :id => "flash_#{name}" %>
</div>

sample/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= render "layouts/message", msg: msg, name: name %>
  <% elsif msg.is_a?(Array) %>
    <% msg.each_with_index do |str, index| %>
      <%= render "layouts/message", msg: str, name: 'notice' %>
    <% end %>
  <% end %>
<% end -%>
<% flash.discard(:notice) %>

sample/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Buckets', root_url, class: 'navbar-brand', title: 'Buckets - 内测版仅供体验，用户数据可能会不定期清空' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if nil and current_user %>
          <li>
            <% if current_user and !current_user.avatar_url.blank? %>
              <%= image_tag current_user.avatar_url, class: 'img-circle navbar-avatar', alt: current_user.nickname %>
            <% else %>
              <span class="glyphicon glyphicon-user navbar-avatar">
              </span>
            <% end %>
          </li>
          <li>
            <p class="navbar-text"> <%= current_user.nickname %> </p>
          </li>
          <li>
            <%= link_to messages_path, title: '提醒' do %>
              <span class="glyphicon glyphicon-bell">
              </span>
              <% if current_user.notifies.unread.any? %>
                <span class="badge"><%= current_user.notifies.unread.count %></span>
              <% end %>
            <% end -%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

sample/app/views/layouts/_navigation_links.html.haml
%li= link_to '交互收藏演示', photos_path
%li= link_to '经典收藏演示', projects_path

sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mindpin Buckets Demo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mindpin Buckets Demo" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield(:head) %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".bs-docs-sidebar" class="page-demo">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container" id="container">
        <div id="messages">
          <%= render 'layouts/messages' %>
        </div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

sample/app/views/photos/_form.html.haml
= simple_form_for(@photo) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

sample/app/views/photos/index.html.haml
%h1.page-header 交互收藏演示
.p15.bg-info 请新建一个图片，然后进入详情页面试用
%p

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th ID
      %th
      %th

  %tbody
    - @photos.each do |photo|
      %tr
        %td= link_to photo.id, photo
        %td= link_to '修改', edit_photo_path(photo)
        %td= link_to '删除', photo, :method => :delete, :data => { :confirm => '你确定?' }

%br

%a.btn.btn-primary{href: (new_photo_path)} 新建图片

sample/app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

sample/app/views/photos/show.html.haml
.bucketerize{data: {rel: "bucketerize", bucketerize: {mode: 'multi', resource_type: 'Photo', resource_id: @photo.id, bucket_type: 'Folder'}}}
  .unhas
    %button.btn.btn-info 添加到Folder
  .has
    %button.btn.btn-default 已添加到Folder

%p

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path

sample/app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

sample/app/views/projects/index.html.haml
%h1.page-header 经典收藏演示
.p15.bg-info 请新建一个项目，然后进入详情页面试用
%p

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th ID
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= link_to project.id, project
        %td= link_to '修改', edit_project_path(project)
        %td= link_to '删除', project, :method => :delete, :data => { :confirm => '你确定?' }

%br

%a.btn.btn-primary{href: (new_project_path)} 新建项目

sample/app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

sample/app/views/projects/show.html.haml
.bucketerize{data: {rel: "bucketerize", bucketerize: {mode: 'standard', resource_type: 'Project', resource_id: @project.id}}}
  .unhas
    %button.btn.btn-default 收藏
  .has
    %button.btn.btn-info 已收藏

%p

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path